on:
  workflow_dispatch:
  push:
    branches:
      - main

name: ğŸš€ Build And Deploy website on push
jobs:
  build_and_Web-deploy:
    name: ğŸ­ Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build --if-present

      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: "puyosim"
          server: "49.212.198.106"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: "./dist/*"
          remote_path: "/home/puyosim/www/new"
          sftpArgs: "-o ConnectTimeout=5"
